import "./globals.css"
import Providers from "./providers"
import Nav from "./nav"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    "color-scheme": "dark light",
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="">
        <Providers>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  )
}
